### ISSUE TITLE
Regex LDAP Authenticator does not work

### ISSUE THREAD

**Issue by Future998** [VirtualCable/openuds#83]
Regex LDAP Authenticator does not work in version 3.6.0.
I have a server configured with Samba DC. I am trying to configure this authenticator. Everything works without SSL, but if I turn it on (changing all the related parameters), I press the "Test" button, an error appears:
`Test failed: option error`
In the server logs:
```ERROR 2023-07-13 13:53:01,193 ldaputil connection 156 Exception connection:
Traceback (most recent call last):
  File "/usr/share/openuds/uds/core/util/ldaputil.py", line 148, in connection
    l.set_option(ldap.OPT_X_TLS_NEWCTX, 0)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/ldap/ldapobject.py", line 698, in set_option
    return self._ldap_call(self._l.set_option,option,invalue)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^
ValueError: option error
ERROR 2023-07-13 13:53:01,193 ldaputil connection 156 Exception connection:
Traceback (most recent call last):
  File "/usr/share/openuds/uds/core/util/ldaputil.py", line 148, in connection
    l.set_option(ldap.OPT_X_TLS_NEWCTX, 0)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/ldap/ldapobject.py", line 698, in set_option
    return self._ldap_call(self._l.set_option,option,invalue)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^
ValueError: option error
```
Why can this error occur?

**Comment by dkmstr** [comment]
Which ldap package do you use? python-ldap.
I have it working fine on Debian, with python-ldap module, (BTW, using GNUTLS library for building python-ldap)...

Try from an python or an ipython, something like this:

Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ldap

In [2]: ldap.OPT_X_TLS_NEWCTX
Out[2]: 24591

In [3]: ldap.__version__
Out[3]: '3.4.3'

It's something related to the python-ldap library by sure...

You will get probably same output (because if the variable is not defined, it will probably get an error).

I think the problem could come that you may be using "openssl" python library (the one used by python-ldap), and i have done it with gnutls version.

look:
~/projects/uds/4.0/openuds/apps-server_enterprise/ ldd ../../env/lib/python3.11/site-packages/_ldap.cpython-311-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffe4b16a000)
        libldap-2.5.so.0 => /lib/x86_64-linux-gnu/libldap-2.5.so.0 (0x00007fdd239bf000)
        liblber-2.5.so.0 => /lib/x86_64-linux-gnu/liblber-2.5.so.0 (0x00007fdd239af000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdd237ce000)
        libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fdd237b1000)
        libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fdd23400000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdd23a52000)
        libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fdd2367b000)
        libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007fdd2364a000)
        libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007fdd2324a000)
        libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fdd23635000)
        libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007fdd231fc000)
        libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007fdd231b3000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fdd23132000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007fdd23627000)
This is my python-ldap bynary module (you can see, it use "libgnutls".

If yours is SSL, the problem are the Ciphers. Default settings file uses very strong cyphers, but using GNUTLS naming convention, here:

https://github.com/VirtualCable/openuds/blob/bd7faf786747b740f3e90c8921402870e049ea9c/server/src/server/settings.py.sample#L176

You can try, first, as single thing, commenting out this line:

https://github.com/VirtualCable/openuds/blob/bd7faf786747b740f3e90c8921402870e049ea9c/server/src/uds/core/util/ldaputil.py#L146

Or removing for testing the full "set-ciphers" part of the code.

Please, also note that if the ciphers are not defined on settings file, these are the ones used (again, for GNUTLS):

https://github.com/VirtualCable/openuds/blob/bd7faf786747b740f3e90c8921402870e049ea9c/server/src/uds/core/util/ldaputil.py#L55

Hope this helps.

Regards

**Comment by dkmstr** [comment]
Yes, i thing the problem is that your libldap is compiled against libssl.
Look, from an altlinux10:

[root@altlinux ~]# ls -la /usr/lib64/python3/site-packages/_ldap.cpython-39.so
-rw-r--r-- 1 root root 74560 Jul  6  2020 /usr/lib64/python3/site-packages/_ldap.cpython-39.so
[root@altlinux ~]# ldd /usr/lib64/python3/site-packages/_ldap.cpython-39.so
        linux-vdso.so.1 (0x00007ffc6b9f7000)
        libldap_r-2.4.so.2 => /usr/lib64/libldap_r-2.4.so.2 (0x00007f78c0ece000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f78c0eba000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f78c0e99000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f78c0cc0000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f78c0ca6000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f78c0c87000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f78c0bf2000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f78c0916000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f78c0f61000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f78c0910000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f78c08d9000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f78c08bb000)

As you can si, it shoes "libssl" instead of "libgnutls", so fixin up ciphers should work (for example, from here: https://developers.cloudflare.com/ssl/reference/cipher-suites/recommendations/)

Let me know how it goes,

Regards,

**Comment by dkmstr** [comment]
Looking at python-ldap code, i see why the ldap.OPT_X_TLS_PROTOCOL... vars are missing... It's due the the libldap version..
Look:
https://github.com/python-ldap/python-ldap/blob/91e0918f822e5a28d5b66b0bdf9b99b596f5be3c/Lib/ldap/constants.py#L307C13-L307C13

Alt linux 10.1 has 2.4 release, as you can see on previos post.
Anyway, with the fix, UDS will not be able to set the minumum TLS version, but if you use valid OpenSSL ciphers, i think that will work, or it should at least :)

**Comment by dkmstr** [comment]
Glad that this helped :).
BTW, i have merged your PR on udsactor.
Did you used OpenSSL ciphers?

**Comment by Future998** [comment]
Yes, I used:
`LDAP_CIPHER_SUITE = 'HIGH:-SSLv2:-SSLv3:-TLSv1.0:-TLSv1.1:+TLSv1.2:+TLSv1.3'`

**Comment by dkmstr** [comment]
Thank you very much!, just to check the cipher suite for OpenSSL python-ldap version and leave it here (probably, i'll include it on sample file ;-)

Thanks a lot!!
