### ISSUE TITLE
"Invalid private key" running manage.py

### ISSUE THREAD

**Issue by jonsito** [VirtualCable/openuds#92]
Hi all,
Trying to install openuds 3.6 in ubuntu 20.04 (python 3.8, Django 4.2.6)

I've (pip) installed all dependencies related in requirements.txt with no error(s)

Also, as (tiny) doc says, to install db I've create mysql database, dbuser and permissions (grant all) and edited settings.py to put db related data into code

running python3 manage.py sync get following trace:

```
root@openuds:/home/cdc/openuds-release-v3.6/server/src# python3 manage.py sync

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cdc/openuds-release-v3.6/server/src/uds/models/__init__.py", line 46, in <module>
    from .service import Service
  File "/home/cdc/openuds-release-v3.6/server/src/uds/models/service.py", line 42, in <module>
    from uds.core import services
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/services/__init__.py", line 41, in <module>
    from .provider import ServiceProvider
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/services/provider.py", line 40, in <module>
    from uds.core.util.config import GlobalConfig
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/util/config.py", line 335, in <module>
    class GlobalConfig:
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/util/config.py", line 392, in GlobalConfig
    SUPER_USER_PASS: Config.Value = Config.section(SECURITY_SECTION).valueCrypt(
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/util/config.py", line 245, in valueCrypt
    return Config.value(self, key, default, True, **kwargs)
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/util/config.py", line 266, in value
    return Config.Value(section, key, default, crypt, longText, **kwargs)
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/util/config.py", line 106, in __init__
    self._default = cryptoManager().encrypt(default)
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/managers/__init__.py", line 50, in cryptoManager
    return CryptoManager.manager()
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/managers/crypto.py", line 97, in manager
    return CryptoManager()  # Singleton pattern will return always the same instance
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/util/singleton.py", line 9, in __call__
    self.__instance = super().__call__(*args, **kwargs)
  File "/home/cdc/openuds-release-v3.6/server/src/uds/core/managers/crypto.py", line 72, in __init__
    self._rsa = serialization.load_pem_private_key(
  File "/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/primitives/serialization/base.py", line 25, in load_pem_private_key
    return ossl.load_pem_private_key(
  File "/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 747, in load_pem_private_key
    return self._load_key(
  File "/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 942, in _load_key
    return self._evp_pkey_to_private_key(
  File "/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 521, in _evp_pkey_to_private_key
    return _RSAPrivateKey(
  File "/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/rsa.py", line 386, in __init__
    raise ValueError("Invalid private key", errors)
ValueError: ('Invalid private key', [<OpenSSLError(code=33554558, lib=4, reason=126, reason_text=iqmp not inverse of q)>])

```

Any ideas? notice that I've left SECRET_KEY and RSA_KEY  unchanged in settings.py

Thanks  in advance.
Juan Antonio

**Comment by dkmstr** [comment]
BTW, Alt linux contains a package With OpenUDS already packaged, if you want to give it a try ;-)

**Comment by jonsito** [comment]
fine. 
created key with

`openssl genrsa -aes128 --passout file:/tmp/rsa.pass 3072 >/tmp/rsa.key`

And inserted key and password into settings.py
Also I had to replace line 73 in server/src/uds/core/managers/crypto.c:

```
#            settings.RSA_KEY.encode(), password=None, backend=default_backend()
            settings.RSA_KEY.encode(), password=settings.SECRET_KEY.encode(), backend=default_backend()
```
Let's continue :-). Thanks
Juan Antonio

**Comment by dkmstr** [comment]
Take care, SECRET_KEY is not related in fact to RSA_KEY, but Django session and cookies protection.
You can add a "password" to the RSA private key, but, due to the fact that both are in same place, this is a nonsense, at least from as security point :)

https://docs.djangoproject.com/en/4.2/topics/signing/

So, i recommend you to generate a sufficient big key (2048 bits or more, as you have done using 3072, is perfect :) ), but without a password. This key is used to encode all passwords on DB for providers, etc...

Hope this helps ;-)
